### ISSUE TITLE
pip install fails

### ISSUE THREAD

**Issue by ernestoongaro** [josephaxisa/henry#5]
Python 2.7.15, pip 18.0, mac os 10.13.4
```
MacBook-Pro-2:~ looker$ pip install henry
Collecting henry
  Could not find a version that satisfies the requirement henry (from versions: )
No matching distribution found for henry
```

**Comment by ernestoongaro** [comment]
Tried 
```pip-3.4 install henry
pip-3.4 install henry
Collecting henry
  Could not find a version that satisfies the requirement henry (from versions: )
No matching distribution found for henry
You are using pip version 10.0.0, however version 18.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Comment by josephaxisa** [comment]
@vinaybabunaidu is your error exactly the same as Ernesto's? If not, can you please paste it here?

**Comment by josephaxisa** [comment]
I managed to reproduce both of the above. The current `setup.py` requires python 3.6 or later, just because that's what I developed on. The tool will definitely not work on python 2.x however I will test on earlier interpreters and relax the version restriction accordingly.

**Comment by rubenhekster** [comment]
@josephaxisa Thanks a lot, that indeed worked for me, however now it says:
![image](https://user-images.githubusercontent.com/33347314/45496450-c17c3700-b775-11e8-8b42-5a3351383647.png)
Any idea?

**Comment by josephaxisa** [comment]
@rubenhekster `pip3 install setuptools` should solve that.

**Comment by mannybhatia** [comment]
+1 

Same error as above  ( Mac 10.13, Python 2.7, PIP 18)

Collecting henry
  Could not find a version that satisfies the requirement henry (from versions: )
No matching distribution found for henry

**Comment by TakesTheBiscuit** [comment]
> +1
> 
> Same error as above ( Mac 10.13, Python 2.7, PIP 18)
> 
> Collecting henry
> Could not find a version that satisfies the requirement henry (from versions: )
> No matching distribution found for henry

@mannybhatia :
https://realpython.com/installing-python/

```
The current setup.py requires python 3.6 or later
```
